# ???ng d?n k?t n?i ??n database auction_db trên máy cá nhân
db.url=jdbc:mysql://localhost:3306/auction_db

# Tên ??ng nh?p MySQL (th??ng m?c ??nh là root)
db.username=root

# M?t kh?u MySQL c?a b?n (Thay ph?n ch? bên d??i thành m?t kh?u th?t)
db.password=123456