apiVersion: v1
kind: Service
metadata:
  name: auction-server
  labels:
    app: auction-server
spec:
  selector:
    app: auction-server
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: websocket
      port: 8081
      targetPort: websocket
  type: ClusterIP
